Repository palvarezc/cavendish-particle-tracks, pull requests merged in 2024-08, with the labels that each got.

#65 Added 2 new error messages and a launch debug script.
  src/cavendish_particle_tracks/_widget.py
  tests/test_widget.py
Labels: enhancement

#54 Resolved to-be-deprecated UI reference.
  .pre-commit-config.yaml
  README.md
  src/cavendish_particle_tracks/_stereoshift_dialog.py
Labels: bug

#79 Reenable tests on MacOS.
  .github/workflows/test_and_deploy.yml
Labels: testing

#81 Add you to contributors!
  CONTRIBUTING.md
  LICENSE.md
  pyproject.toml
Labels: documentation

#85 Add pytest fixture to set up the `ParticleTracksWidget`.
  tests/conftest.py
  tests/test_decay_angles_dialog.py
  tests/test_save.py
  tests/test_stereoshift_dialog.py
  tests/test_widget.py
Labels: enhancement, testing

#101 Update ruff, black, and mypy linting.
  .pre-commit-config.yaml
  docs/conf.py
  pyproject.toml
  tests/conftest.py
  tests/test_calculation_functions.py
  tests/test_stereoshift_dialog.py
Labels: testing

#102 Specify installation instructions for macOS.
  README.md
Labels: documentation, enhancement, question

#94 Added axis label.
  src/cavendish_particle_tracks/_widget.py
Labels: enhancement

#100 Images are now 4D
  .pre-commit-config.yaml
  README.md
  docs/conf.py
  pyproject.toml
  src/cavendish_particle_tracks/_analysis.py
  src/cavendish_particle_tracks/_decay_angles_dialog.py
  src/cavendish_particle_tracks/_set_fiducial_dialog.py
  src/cavendish_particle_tracks/_stereoshift_dialog.py
  src/cavendish_particle_tracks/_widget.py
  tests/conftest.py
  tests/test_calculation_functions.py
  tests/test_decay_angles_dialog.py
  tests/test_save.py
  tests/test_stereoshift_dialog.py
  tests/test_widget.py
Labels: enhancement
