Repository palvarezc/cavendish-particle-tracks, pull requests merged in 2024-09, with the labels that each got.

#90 Enable/disable calculation buttons based on decay selected in table
  src/cavendish_particle_tracks/_analysis.py
  src/cavendish_particle_tracks/_decay_angles_dialog.py
  src/cavendish_particle_tracks/_stereoshift_dialog.py
  src/cavendish_particle_tracks/_widget.py
  tests/test_save.py
  tests/test_stereoshift_dialog.py
  tests/test_widget.py
Labels: enhancement

#106 User manual
  CONTRIBUTING.md
  README.md
  docs/index.rst
  docs/user-manual.md
  pyproject.toml
Labels: documentation, core

#115 Use context manager as recommended in deprecation warning.
  tests/test_decay_angles_dialog.py
Labels: testing, minor issue

#117 Update napari dependency, update actions versions, and test python 3.12.
  .github/workflows/test_and_deploy.yml
  pyproject.toml
  src/cavendish_particle_tracks/_calculate.py
  src/cavendish_particle_tracks/_magnification_dialog.py
  src/cavendish_particle_tracks/_widget.py
  tests/conftest.py
Labels: testing

#127 Remove API docs from the website, add a GitHub logo link, and update some outdated things.
  CONTRIBUTING.md
  README.md
  docs/api.rst
  docs/index.rst
  pyproject.toml
Labels: documentation, enhancement, minor issue

#128 Avoid tool duplication
  src/cavendish_particle_tracks/_decay_angles_dialog.py
  src/cavendish_particle_tracks/_magnification_dialog.py
  src/cavendish_particle_tracks/_stereoshift_dialog.py
  src/cavendish_particle_tracks/_widget.py
  tests/test_decay_angles_dialog.py
  tests/test_magnification_dialog.py
  tests/test_stereoshift_dialog.py
Labels: enhancement

#134 Add version to installation instructions in README.
  README.md
Labels: documentation

#137 Don't actually want to try deploying to pypi.
  .github/workflows/lint_and_test.yml
Labels: bug, minor issue

#138 Offer save data dialog on widget closure
  src/cavendish_particle_tracks/_widget.py
  tests/test_widget.py
Labels: core, testing

#132 Tidy up names, expand tlas and abbvns, correct docstrings, and refactor the magnification dialog's constructor
  src/cavendish_particle_tracks/__init__.py
  src/cavendish_particle_tracks/_analysis.py
  src/cavendish_particle_tracks/_decay_angles_dialog.py
  src/cavendish_particle_tracks/_magnification_dialog.py
  src/cavendish_particle_tracks/_main_widget.py
  src/cavendish_particle_tracks/_stereoshift_dialog.py
  src/cavendish_particle_tracks/napari.yaml
  tests/conftest.py
  tests/test_decay_angles_dialog.py
  tests/test_magnification_dialog.py
  tests/test_save.py
  tests/test_stereoshift_dialog.py
  tests/test_widget.py
Labels: documentation, enhancement

#143 Prevent crash due to view rotation.
  src/cavendish_particle_tracks/_main_widget.py
Labels: bug, enhancement, user feedback

#131 Button hiding logic and new UI for bottom docking
  launch_debug.py
  src/cavendish_particle_tracks/_main_widget.py
  tests/test_widget.py
Labels: enhancement

#153 Reshuffle the data and show first event
  src/cavendish_particle_tracks/_analysis.py
  src/cavendish_particle_tracks/_main_widget.py
  tests/test_widget.py
Labels: enhancement, core

#160 Add launcher to startup in Windows on lab machines
  windows/cavendish_particle_tracks.bat
Labels: core

#157 Control data shuffling with an environment variable
  src/cavendish_particle_tracks/_main_widget.py
  tests/test_env.py
Labels: enhancement

#162 Missing -e in docs contribution instructions.
  CONTRIBUTING.md
Labels: bug, documentation, enhancement

#174 Suppress the `FutureWarning`s from `napari`.
  src/cavendish_particle_tracks/_main_widget.py
Labels: usability

#168 Don't move dialogs when opening them.
  src/cavendish_particle_tracks/_main_widget.py
Labels: bug, usability

#173 Remove ascii art.
  launch_debug.py
  src/cavendish_particle_tracks/_main_widget.py
  tests/test_widget.py
Labels: bug, core, usability

#166 Relax line length
  pyproject.toml
  src/cavendish_particle_tracks/_calculate.py
  src/cavendish_particle_tracks/_decay_angles_dialog.py
  src/cavendish_particle_tracks/_magnification_dialog.py
  src/cavendish_particle_tracks/_main_widget.py
  src/cavendish_particle_tracks/_stereoshift_dialog.py
  tests/test_decay_angles_dialog.py
  tests/test_env.py
  tests/test_magnification_dialog.py
  tests/test_misc.py
  tests/test_save.py
  tests/test_stereoshift_dialog.py
  tests/test_widget.py
Labels: enhancement, question, minor issue

#167 Add titles to decay angles dialog table.
  src/cavendish_particle_tracks/_decay_angles_dialog.py
Labels: enhancement, minor issue, usability

#175 Neaten up constants and move getting settings from env out of the main widget.
  src/cavendish_particle_tracks/_decay_angles_dialog.py
  src/cavendish_particle_tracks/_magnification_dialog.py
  src/cavendish_particle_tracks/_main_widget.py
  src/cavendish_particle_tracks/_settings.py
  tests/test_decay_angles_dialog.py
  tests/test_magnification_dialog.py
  tests/test_widget.py
Labels: enhancement, minor issue

#172 Data corruption on radius and length measurements
  src/cavendish_particle_tracks/_main_widget.py
  src/cavendish_particle_tracks/analysis.py
  tests/test_stereoshift_dialog.py
  tests/test_widget.py
Labels: bug, core

#155 Allow two measurements of the stereoshift for each particle decay
  src/cavendish_particle_tracks/_main_widget.py
  src/cavendish_particle_tracks/_stereoshift_dialog.py
  src/cavendish_particle_tracks/analysis.py
  tests/test_decay_angles_dialog.py
  tests/test_stereoshift_dialog.py
Labels: core

#154 Make the measurements layer 4D
  src/cavendish_particle_tracks/_main_widget.py
  src/cavendish_particle_tracks/analysis.py
  tests/test_main_measurements.py
  tests/test_stereoshift_dialog.py
  tests/test_widget.py
Labels: enhancement, usability

#152 Lock decay angles tracks to common vertex.
  src/cavendish_particle_tracks/_calculate.py
  src/cavendish_particle_tracks/_decay_angles_dialog.py
  tests/test_calculation_functions.py
  tests/test_decay_angles_dialog.py
Labels: enhancement, usability

#177 Adding feedback to the user on calculation of magnification and stereoshift
  src/cavendish_particle_tracks/_magnification_dialog.py
  src/cavendish_particle_tracks/_stereoshift_dialog.py
Labels: enhancement, usability

#182 Take the "bypass button disable" option from the environment.
  launch_debug.py
  src/cavendish_particle_tracks/_main_widget.py
  src/cavendish_particle_tracks/_settings.py
  tests/test_env.py
  tests/test_widget.py
Labels: enhancement

#181 Get the widget ready for the labs
  windows/CPT.ico
  windows/cavendish_particle_tracks.bat
  windows/start_cpt.py
Labels: cavendish

#161 Update documentation
  docs/user-manual.md
Labels: documentation, enhancement

#183 Update the README for v1.
  README.md
Labels: documentation, core
